server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  jwt:
    secret: "change-me-to-strong-secret"
    expiration-ms: 3600000
